# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f0cc908e2f531b696c4920401b1f9f7e0fa807986380e00d44b2e993c336231328ce294b7236be40f8efb164bf8b01f78696a5c208f3aa391515fc409aa681d8

test:
  secret_key_base: f71ba645b801eb3c55596d829f59734f303d667451a7d95b98adf7ddb297913264e8c140a90bb4eb2f3c12c06ae532873642bfc627dbf04b8303383e0fadcd74

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
